version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simpleproject_db
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql

  simple-project-app:
    build: .
    ports:
      - "8086:8086"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/simpleproject_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysqldb_data:
